export const cardSuperMario =[
    {images: '/img/luigi.png' },
    {images: '/img/bowser.png' },
    {images: '/img/carnivora.png'},
    {images: '/img/dasy.png' },
    {images: '/img/gomba.png' },
    {images: '/img/mario.png' },
    {images: '/img/peach.png' },
    {images: '/img/seta.png' },
    {images: '/img/toad.png' },
    {images: '/img/yoshi.png' },
    {images: '/img/mario.png' },
    {images: '/img/luigi.png' },
    {images: '/img/bowser.png' },
    {images: '/img/dasy.png' },
    {images: '/img/carnivora.png' },
    {images: '/img/peach.png' },
    {images: '/img/toad.png' },
    {images: '/img/yoshi.png' },
    {images: '/img/seta.png' },
    {images: '/img/gomba.png' },
]